version: '3.8'

services:
  db_django:
    image: postgres:13
    container_name: postgres_django
    environment:
      POSTGRES_DB: ${DB_NAME_DJANGO}
      POSTGRES_USER: ${DB_USER_DJANGO}
      POSTGRES_PASSWORD: ${DB_PASSWORD_DJANGO}
    volumes:
      - postgres_data_django:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.13
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db_django
    networks:
      - app-network

  django:
    build:
      context: .
    container_name: django_core
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py initialize_prices &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db_django
    networks:
      - app-network


  tests:
    build:
      context: .
    container_name: django_tests
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py test"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      USE_SQLITE: 'False'
    depends_on:
      - db_django
    networks:
      - app-network


networks:
  app-network:
    external: true

volumes:
  postgres_data_django:
